version: '3.8'
services:
  redis:
    image: redis:7
    container_name: diagnostic_redis
    ports:
      - "6379:6379"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diagnostic_backend
    environment:
      - PORT=4000
      - NODE_ENV=development
    ports:
      - "4000:4000"
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app
