version: '3.8'
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ../backend:/usr/src/app
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
